use std::env;
use std::fs;
use std::process::Command;

use serde::Deserialize;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let blog_dir = format!("{}/blog", manifest_dir);

    let mut files: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&blog_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |e| e == "md") {
                if let Some(stem) = path.file_stem() {
                    files.push(stem.to_string_lossy().to_string());
                }
            }
        }
    }

    files.sort();

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = format!("{}/blog_posts.rs", out_dir);

    let mut code = String::from("// Auto-generated by build.rs — DO NOT EDIT\n\n");

    for file in &files {
        let safe_stem = file.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
        let const_name = format!("POST_{}", safe_stem.to_uppercase());
        let abs_path = format!("{}/blog/{}.md", manifest_dir, file);
        code.push_str(&format!(
            "pub const {const_name}: &str = include_str!(\"{abs_path}\");\n",
        ));
    }

    code.push_str("\npub const ALL_BLOG_FILES: &[(&str, &str)] = &[\n");
    for file in &files {
        let safe_stem = file.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
        let const_name = format!("POST_{}", safe_stem.to_uppercase());
        code.push_str(&format!("    (\"{file}\", {const_name}),\n"));
    }
    code.push_str("];\n");

    fs::write(&dest, code).unwrap();

    println!("cargo:rerun-if-changed=blog/");

    // Copy robots.txt to the public directory
    let robots_src = format!("{manifest_dir}/robots.txt");
    let _ = fs::copy(&robots_src, format!("{manifest_dir}/public/robots.txt"));
    println!("cargo:rerun-if-changed=robots.txt");

    // Copy blog _assets into the public directory so Dioxus serves them
    let blog_assets_dir = format!("{manifest_dir}/blog/_assets");
    let dest_assets_dir = format!("{manifest_dir}/public/assets/blog");
    if let Ok(entries) = fs::read_dir(&blog_assets_dir) {
        let _ = fs::create_dir_all(&dest_assets_dir);
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() {
                let dest = format!("{}/{}", dest_assets_dir, path.file_name().unwrap().to_string_lossy());
                let _ = fs::copy(&path, &dest);
            }
        }
    }
    println!("cargo:rerun-if-changed=blog/_assets/");

    // Fetch GitHub data
    fetch_github_data(&out_dir);
}

// ── GitHub data fetching ──────────────────────────────────────────────

const USERNAME: &str = "metruzanca";

#[derive(Deserialize)]
#[allow(non_snake_case)]
struct GraphQLResponse {
    data: Option<GraphQLData>,
}

#[derive(Deserialize)]
struct GraphQLData {
    user: Option<GraphQLUser>,
}

#[derive(Deserialize)]
#[allow(non_snake_case)]
struct GraphQLUser {
    #[serde(default)]
    pinnedItems: PinnedItems,
    #[serde(default)]
    repositories: Repositories,
    #[serde(default)]
    contributionsCollection: ContributionsCollection,
}

#[derive(Deserialize, Default)]
#[allow(non_snake_case)]
struct ContributionsCollection {
    #[serde(default)]
    contributionCalendar: ContributionCalendar,
}

#[derive(Deserialize, Default)]
struct ContributionCalendar {
    #[serde(default)]
    totalContributions: u32,
    #[serde(default)]
    weeks: Vec<ContributionWeek>,
}

#[derive(Deserialize, Default)]
struct ContributionWeek {
    #[serde(default)]
    contributionDays: Vec<ContributionDay>,
}

#[derive(Deserialize, Default)]
struct ContributionDay {
    #[serde(default)]
    contributionCount: u32,
    #[serde(default)]
    date: String,
}

#[derive(Deserialize, Default)]
struct PinnedItems {
    #[serde(default)]
    nodes: Vec<GraphQLRepo>,
}

#[derive(Deserialize, Default)]
struct Repositories {
    #[serde(default)]
    nodes: Vec<GraphQLRepo>,
}

#[derive(Deserialize)]
#[allow(non_snake_case)]
struct GraphQLRepo {
    name: String,
    description: Option<String>,
    url: String,
    #[serde(default)]
    homepageUrl: Option<String>,
    #[serde(default)]
    stargazerCount: u32,
    #[serde(default)]
    primaryLanguage: Option<Language>,
    #[serde(default)]
    repositoryTopics: Option<RepositoryTopics>,
    #[serde(default)]
    defaultBranchRef: Option<DefaultBranchRef>,
    #[serde(default)]
    isFork: bool,
    #[serde(default)]
    isPrivate: bool,
}

#[derive(Deserialize)]
#[allow(non_snake_case)]
struct DefaultBranchRef {
    target: Option<CommitTarget>,
}

#[derive(Deserialize)]
#[allow(non_snake_case)]
struct CommitTarget {
    #[serde(default)]
    committedDate: Option<String>,
    #[serde(default)]
    history: History,
}

#[derive(Deserialize, Default)]
#[allow(non_snake_case)]
struct History {
    #[serde(default)]
    totalCount: u32,
}

#[derive(Deserialize)]
struct Language {
    name: String,
    #[serde(default)]
    color: Option<String>,
}

#[derive(Deserialize)]
struct RepositoryTopics {
    #[serde(default)]
    nodes: Vec<TopicNode>,
}

#[derive(Deserialize)]
struct TopicNode {
    topic: Topic,
}

#[derive(Deserialize)]
struct Topic {
    name: String,
}

struct RepoData {
    name: String,
    description: String,
    url: String,
    homepage: Option<String>,
    stars: u32,
    commit_count: u32,
    language: Option<String>,
    language_color: Option<String>,
    topics: Vec<String>,
    committed_date: Option<String>,
}

fn get_github_token() -> Option<String> {
    if let Ok(token) = env::var("GITHUB_TOKEN") {
        let token = token.trim().to_string();
        if !token.is_empty() {
            return Some(token);
        }
    }
    // gh cli fallback for local development
    if let Ok(output) = Command::new("gh").args(["auth", "token"]).output() {
        if output.status.success() {
            let token = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !token.is_empty() {
                return Some(token);
            }
        }
    }
    None
}

fn fetch_github_data(out_dir: &str) {
    let dest = format!("{}/github_repos.rs", out_dir);

    let token = match get_github_token() {
        Some(t) => t,
        None => {
            println!(
                "cargo:warning=GITHUB_TOKEN not set and gh CLI not available — \
                 generating empty GitHub data (CONTRIBUTION_TOTAL=0, CONTRIBUTION_CELLS empty)"
            );
            let empty = "// No GitHub token available\n\
                         pub const PINNED_REPOS: &[GithubRepo] = &[];\n\
                         pub const ALL_REPOS: &[GithubRepo] = &[];\n\
                         pub const CONTRIBUTION_TOTAL: u32 = 0;\n\
                         pub const CONTRIBUTION_CELLS: &[ContributionCell] = &[];\n";
            fs::write(&dest, empty).unwrap();
            return;
        }
    };

    let (pinned, all, contribution_total, contribution_cells) = fetch_all(&token);
    match (&pinned, &all) {
        (Ok(p), Ok(a)) => eprintln!(
            "Fetched {} pinned, {} total repos, {} contributions from GitHub",
            p.len(),
            a.len(),
            contribution_total
        ),
        _ => {}
    }

    let mut code = String::from("// Auto-generated by build.rs — DO NOT EDIT\n\n");

    code.push_str("pub const PINNED_REPOS: &[GithubRepo] = &[\n");
    if let Ok(ref repos) = pinned {
        for repo in repos {
            code.push_str(&format_repo(repo));
        }
    }
    code.push_str("];\n\n");

    code.push_str("pub const ALL_REPOS: &[GithubRepo] = &[\n");
    if let Ok(ref repos) = all {
        for repo in repos {
            code.push_str(&format_repo(repo));
        }
    }
    code.push_str("];\n\n");

    code.push_str(&format!(
        "pub const CONTRIBUTION_TOTAL: u32 = {contribution_total};\n"
    ));
    code.push_str("pub const CONTRIBUTION_CELLS: &[ContributionCell] = &[\n");
    for (level, count, date) in &contribution_cells {
        let d = escape_rust_string(date);
        code.push_str(&format!(
            "    ContributionCell {{ level: {level}, count: {count}, date: \"{d}\" }},\n"
        ));
    }
    code.push_str("];\n");

    fs::write(&dest, code).unwrap();
}

fn fetch_all(
    token: &str,
) -> (
    Result<Vec<RepoData>, String>,
    Result<Vec<RepoData>, String>,
    u32,
    Vec<(u8, u32, String)>,
) {
    let query = format!(
        r#"query($login: String!) {{ user(login: $login) {{ pinnedItems(first: 6, types: REPOSITORY) {{ nodes {{ ... on Repository {{ name description url homepageUrl stargazerCount primaryLanguage {{ name color }} repositoryTopics(first: 10) {{ nodes {{ topic {{ name }} }} }} defaultBranchRef {{ target {{ ... on Commit {{ history {{ totalCount }} }} }} }} }} }} }} repositories(first: 100, orderBy: {{field: PUSHED_AT, direction: DESC}}, affiliations: [OWNER]) {{ nodes {{ name description url homepageUrl stargazerCount primaryLanguage {{ name color }} repositoryTopics(first: 10) {{ nodes {{ topic {{ name }} }} }} defaultBranchRef {{ target {{ ... on Commit {{ committedDate history {{ totalCount }} }} }} }} isFork isPrivate }} }} contributionsCollection {{ contributionCalendar {{ totalContributions weeks {{ contributionDays {{ contributionCount date }} }} }} }} }} }}"#,
    );

    let parsed: GraphQLResponse = {
        let rt = tokio::runtime::Runtime::new().expect("Failed to create tokio runtime");
        let token = token.to_string();
        match rt.block_on(async {
            let octocrab = octocrab::OctocrabBuilder::new()
                .personal_token(token)
                .build()
                .map_err(|e| format!("Failed to build octocrab client: {e}"))?;

            let json: serde_json::Value = octocrab
                .graphql(&serde_json::json!({
                    "query": query,
                    "variables": { "login": USERNAME }
                }))
                .await
                .map_err(|e| format!("GraphQL request failed: {e}"))?;

            serde_json::from_value(json).map_err(|e| format!("GraphQL parse failed: {e}"))
        }) {
            Ok(p) => p,
            Err(msg) => {
                eprintln!("cargo:warning={msg}");
                return (Err(msg.clone()), Err(msg), 0, vec![]);
            }
        }
    };

    let user = match parsed.data.and_then(|d| d.user) {
        Some(u) => u,
        None => {
            let msg = "No user data in GraphQL response".to_string();
            eprintln!("cargo:warning={msg}");
            return (Err(msg.clone()), Err(msg), 0, vec![]);
        }
    };

    let pinned: Vec<RepoData> = user
        .pinnedItems
        .nodes
        .into_iter()
        .map(graphql_to_repo)
        .collect();

    let mut all: Vec<RepoData> = user
        .repositories
        .nodes
        .into_iter()
        .filter(|r| !r.isFork && !r.isPrivate && r.description.is_some())
        .map(graphql_to_repo)
        .collect();
    all.sort_by(|a, b| match (&a.committed_date, &b.committed_date) {
        (Some(a_date), Some(b_date)) => b_date.cmp(a_date),
        (Some(_), None) => std::cmp::Ordering::Less,
        (None, Some(_)) => std::cmp::Ordering::Greater,
        (None, None) => a.name.cmp(&b.name),
    });

    let cal = &user.contributionsCollection.contributionCalendar;
    let contribution_total = cal.totalContributions;
    let contribution_cells: Vec<(u8, u32, String)> = cal
        .weeks
        .iter()
        .flat_map(|w| &w.contributionDays)
        .map(|d| {
            (
                contribution_level(d.contributionCount),
                d.contributionCount,
                format_contribution_date(&d.date),
            )
        })
        .take(52 * 7)
        .collect();

    (Ok(pinned), Ok(all), contribution_total, contribution_cells)
}

fn contribution_level(count: u32) -> u8 {
    match count {
        0 => 0,
        1..=9 => 1,
        10..=19 => 2,
        20..=29 => 3,
        _ => 4,
    }
}

fn format_contribution_date(iso: &str) -> String {
    if iso.len() < 10 {
        return iso.to_string();
    }
    let month = match &iso[5..7] {
        "01" => "Jan",
        "02" => "Feb",
        "03" => "Mar",
        "04" => "Apr",
        "05" => "May",
        "06" => "Jun",
        "07" => "Jul",
        "08" => "Aug",
        "09" => "Sep",
        "10" => "Oct",
        "11" => "Nov",
        "12" => "Dec",
        _ => "",
    };
    let year = &iso[0..4];
    let day = &iso[8..10];
    format!("{month} {day}, {year}")
}

fn graphql_to_repo(r: GraphQLRepo) -> RepoData {
    let topics: Vec<String> = r
        .repositoryTopics
        .map(|rt| rt.nodes.into_iter().map(|n| n.topic.name).collect())
        .unwrap_or_default();

    let committed_date = r
        .defaultBranchRef
        .as_ref()
        .and_then(|d| d.target.as_ref())
        .and_then(|t| t.committedDate.clone());

    let commit_count = r
        .defaultBranchRef
        .as_ref()
        .and_then(|d| d.target.as_ref())
        .map(|t| t.history.totalCount)
        .unwrap_or(0);

    RepoData {
        name: r.name,
        description: r.description.unwrap_or_default(),
        url: r.url,
        homepage: r.homepageUrl.filter(|h| !h.is_empty()),
        stars: r.stargazerCount,
        commit_count,
        language: r.primaryLanguage.as_ref().map(|l| l.name.clone()),
        language_color: r
            .primaryLanguage
            .as_ref()
            .and_then(|l| l.color.clone())
            .filter(|c| !c.is_empty()),
        topics,
        committed_date,
    }
}

fn format_repo(repo: &RepoData) -> String {
    let desc = escape_rust_string(&repo.description);
    let name = escape_rust_string(&repo.name);
    let url = escape_rust_string(&repo.url);

    let homepage = match &repo.homepage {
        Some(h) => format!(r#"Some("{}")"#, escape_rust_string(h)),
        None => "None".to_string(),
    };

    let language = match &repo.language {
        Some(l) => format!(r#"Some("{}")"#, escape_rust_string(l)),
        None => "None".to_string(),
    };

    let language_color = match &repo.language_color {
        Some(c) => format!(r#"Some("{}")"#, escape_rust_string(c)),
        None => "None".to_string(),
    };

    let committed_date = match &repo.committed_date {
        Some(d) => format!(r#"Some("{}")"#, escape_rust_string(d)),
        None => "None".to_string(),
    };

    let topics_str = if repo.topics.is_empty() {
        "&[]".to_string()
    } else {
        let topics: Vec<String> = repo
            .topics
            .iter()
            .map(|t| format!(r#""{}""#, escape_rust_string(t)))
            .collect();
        format!("&[{}]", topics.join(", "))
    };

    format!(
        "    GithubRepo {{\n\
         \x20       name: \"{name}\",\n\
         \x20       description: \"{desc}\",\n\
         \x20       url: \"{url}\",\n\
         \x20       homepage: {homepage},\n\
         \x20       stars: {stars},\n\
         \x20       commit_count: {commit_count},\n\
         \x20       language: {language},\n\
         \x20       language_color: {language_color},\n\
         \x20       topics: {topics_str},\n\
         \x20       committed_date: {committed_date},\n\
         \x20   }},\n",
        stars = repo.stars,
        commit_count = repo.commit_count,
    )
}

fn escape_rust_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other => out.push(other),
        }
    }
    out
}
