use std::env;
use std::fs;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let blog_dir = format!("{}/blog", manifest_dir);

    let mut files: Vec<String> = Vec::new();
    if let Ok(entries) = fs::read_dir(&blog_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().map_or(false, |e| e == "md") {
                if let Some(stem) = path.file_stem() {
                    files.push(stem.to_string_lossy().to_string());
                }
            }
        }
    }

    files.sort();

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = format!("{}/blog_posts.rs", out_dir);

    let mut code = String::from("// Auto-generated by build.rs — DO NOT EDIT\n\n");

    for file in &files {
        let safe_stem = file.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
        let const_name = format!("POST_{}", safe_stem.to_uppercase());
        let abs_path = format!("{}/blog/{}.md", manifest_dir, file);
        code.push_str(&format!(
            "pub const {const_name}: &str = include_str!(\"{abs_path}\");\n",
        ));
    }

    code.push_str("\npub const ALL_BLOG_FILES: &[(&str, &str)] = &[\n");
    for file in &files {
        let safe_stem = file.replace(|c: char| !c.is_ascii_alphanumeric(), "_");
        let const_name = format!("POST_{}", safe_stem.to_uppercase());
        code.push_str(&format!("    (\"{file}\", {const_name}),\n"));
    }
    code.push_str("];\n");

    fs::write(&dest, code).unwrap();

    println!("cargo:rerun-if-changed=blog/");
}
