pub mod section_heading;
pub mod nav;
pub mod hero;
pub mod projects;
pub mod case_studies;
pub mod writing;
pub mod git_activity;
pub mod contact;
pub mod now_playing;

pub use section_heading::*;
pub use nav::*;
pub use hero::*;
pub use projects::*;
pub use case_studies::*;
pub use writing::*;
pub use git_activity::*;
pub use contact::*;
pub use now_playing::*;
